### ISSUE TITLE
Docs: file and folder import syntax is missing slash seperators

### ISSUE THREAD

**Issue by Kab1r** [harness/terraform-provider-harness#1016]
When importing files and folders, slashes must separate org, project, and resource identifiers.
Documentation suggests no separator:
- https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_file_store_file#import
- https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_file_store_folder#import

**Comment by ritek01** [comment]
Thank you for reporting this issue! I’ll definitely check it out and, if necessary, update the documentation accordingly.
