### ISSUE TITLE
Feature Request for a Next Gen Data Source to access Harness Account ID  

### ISSUE THREAD

**Issue by CMorton737** [harness/terraform-provider-harness#1029]
Hi there,

Currently the Harness Terraform provider has the "harness_current_account" Data Source, which can be used to access the Harness account id of the currently authenticated Harness provider.  

The issue is that harness_current_account is a First Gen resource.  It seems like there is no clean way to pull the current account id with any of the Harness Next Gen resources.

This feature is requesting a new resource, "harness_platform_current_account".
### Terraform Version
terraform 1.5.7

### Affected Resource(s)
- harness_current_account
  - First Gen resource which was [EOS on 3/30/2024.](https://developer.harness.io/docs/category/harness-api-firstgen/)
- harness_platform_current_user
  - Next Gen resource most closely representing what is needed, as it includes an `account_id` attribute .  However, it cannot be used with Harness Service Account API keys. Attempt to use a Harness SA resulted in "Invalid request: Current user can be accessed only by 'USER' principal type" 
- harness_platform_service_account
  - This is one resource which has account_id as a required attribute, creating the use case of needing to fetch the account_id.  Since account_id is a provider-level attribute, it's not always available in the context like org_id or project_id
- harness_platform_current_account
  - This is the resource this feature request is suggesting be added to the provider

### Expected Behavior
```hcl
data "harness_platform_current_account" "this" {}

locals {
  account_id = data.harness_platform_current_account.this.account_id
}
```

### Important Factoids
Yes, the account ID is a required attribute when instantiating the provider, and the case could be made that since you have to provide the account_id regardless, you could use a variable to interact with the value.  However, it's not convenient to explicitly pass the account_id as a variable between modules.  It would be much preferred to simply invoke the harness_platform_current_provider Data Source to access the account_id as needed.  This allows for encapsulation of the account_id concept within modules, abstracting it away from the user

**Comment by rssnyder** [comment]
I have added this to the provider a while back, it's just missing documentation. There is a pending PR here to add them. https://github.com/harness/terraform-provider-harness/pull/1008

You can use it like:
```
data "harness_platform_current_account" "current" {}
```

And reference the ID like:
```
data.harness_platform_current_account.current.id
```
