### ISSUE TITLE
Terraform log on Debug or Trace level is showing Harnes API key in plain text

### ISSUE THREAD

**Issue by arimaverick** [harness/terraform-provider-harness#103]
Hi there,

### Terraform Version
1.0.0

### Affected Resource(s)
NA

### Expected Behavior
Any change in verbosity of the Log level should not show the Harness API key in  X-Api-Key field of the HTTP Request. 

### Actual Behavior
When we turn on the Log level to TRACE or DEBUG level, the log shows Harness API key (X-Api-Key value) in plain text HTTP Request body. 

### Steps to Reproduce

1. export TF_LOG=TRACE
2. `terraform plan` or `terraform apply`
3. Check for X-Api-Key value in any of the HTTP Request body

@abrahamkoshy

**Comment by micahlmartin** [comment]
This is proving to be quite difficult to fix becuase the logging package is separate module that isn't owned by us. We'd have to fork it to add the additional functionality. If this is absolutely critical we're going to have to go back to the drawing board on this.
