### ISSUE TITLE
Docs: harness_platform_file_store_folder and harness_platform_file_store_file should have clearer documentation on parent_identifier

### ISSUE THREAD

**Issue by smacktoid** [harness/terraform-provider-harness#1047]
### Terraform Version
v1.4.4

### Affected Resource(s)
harness_platform_file_store_file 
harness_platform_file_store_folder

### Terraform Configuration Files
```hcl
resource "harness_platform_file_store_folder" "test_service_manifest_folder" {
  org_id      = var.harness_organization_id
  project_id = harness_platform_project.this.id
  identifier        = "test_service_manifest_folder"
  name              = "Test Service Manifest Folder"
  tags              = ["service:testservice"]
  parent_identifier = "Root"
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
The docs should make it clear that the identifier of the Root of the harness file store is "Root"

### Actual Behavior
The provider docs did not explain anything. I tried leaving the identifier blank, but it did not help. The error output did not explain any further.

I was only able to find the correct identifier (Root) by checking harness' API docs. I shouldn't have to do that.

### Steps to Reproduce
1. Try to create a folder or file resource at the root level of your project. Provide a blank parent_identifier

**Comment by ritek01** [comment]
Thank @smacktoid , for noticing this and raising the issue! 
I've submitted a PR to update the documentation and clarify the use of `parent_identifier` for root-level entries in the Harness File Store. You can track the PR here: [PR link](https://github.com/harness/terraform-provider-harness/pull/1074).
