### ISSUE TITLE
Bug: resource harness_platform_template creates a template version before file path verification

### ISSUE THREAD

**Issue by bah-joshua-bachman** [harness/terraform-provider-harness#1059]
### Terraform Version
v1.9.5

### Affected Resource(s)
harness_platform_template

### Terraform Configuration Files
```hcl

resource "harness_platform_template" "test1" {
  identifier      = "test"
  name            = "test"
  version         = "v1"
  import_from_git = true
  is_stable = true
  git_import_details {
    branch_name   = "master"
    file_path     = ".harness/test1.yaml" 
    connector_ref = "account.mygitconnector" 
    repo_name     = "my-git-repo"
  }
  template_import_request {
    template_name        = "test"
    template_version     = "v1"
    template_description = "My Template Test"
  }
}

resource "time_sleep" "wait_10_seconds" {
  depends_on       = [harness_platform_template.test1]
  destroy_duration = "10s"
}

resource "harness_platform_template" "test2" {
  identifier      = "test"
  name            = "test"
  version         = "v2"
  import_from_git = true
  is_stable = false
  git_import_details {
    branch_name   = "feature/my-feature-branch"
    file_path     = ".harness/test2.yaml" 
    connector_ref = "account.mygitconnector" 
    repo_name     = "my-git-repo"
  }
  template_import_request {
    template_name        = "test"
    template_version     = "v2"
    template_description = "My Template Test"
  }
   depends_on       = [time_sleep.wait_10_seconds]
}

```

### Expected Behavior
The terraform module should report an error before anything is created to show the user that the file path does not exist in the base branch or allow terraform/harness-nextgen-api to import from the specified git branch instead of the base branch.

### Actual Behavior
A template version tag is created via the template_version_api prior to any git file path checking. Due to terraform/harness nextgen api only searching from a base branch after the initial template is created, this fails but only after a new version is created. When you go to re-apply these resources with the `v2` file in the base branch, the module will again fail because the version `v2` tag has already been created on the template. When you go to destroy these resources, terraform is unaware of the resource due to prior failures and will not destroy the stable version of the template without `force_delete` set to `true` or manual pruning of other version tags associated with the template. 

### Steps to Reproduce
1. Create a template in a git repository for each provided resource (Ensure that these are created in separate branches)
2. `terraform apply` above module
3. Watch for failures
4. Push the file from your feature branch to your master branch
5. Change the branch reference in the `test2` resource to master 
6. `terraform apply` new module
7. Watch for failures. 
8. `terraform destroy`
9. Watch for failures

**Comment by shivamnegi94** [comment]
The issue has been fixed in the most recent Terraform release. The resolution is included in version 0.33.2. Please update to this version to benefit from the fix.
