### ISSUE TITLE
Yaml configurations with multiple metric-thresholds can cause diffs in terraform plan/apply

### ISSUE THREAD

**Issue by jadunham1** [harness/terraform-provider-harness#116]
Hello there.
I am using terraform to template out some complex workflows in harness and running into an ordering issue on yaml files and I think it is because of the API, but not sure if something that should be handled in the go client/terraform.

### Problem
Every time I run terraform apply we see differences using the `harness_yaml_config` even though nothing has changed.
This seems to be specific to workflows with verification providers using metric thresholds (i.e. fail fast if the metric is above 0), haven't run into this issue anywhere else.

### Affected Resource(s)
harness_yaml_config

### Debugging
I have traced this down to the GET call to config as code: `https://app.harness.io/gateway/api/setup-as-code/yaml/workflows/<workflow>?accountId=<account>&appId=<appID>`.  On complex workflows with multiple verification providers I can get different sha256sums on the output.  It seems to flop only between two differences and it's always the ordering on verification providers.  It doesn't seem completely random fwiw and always flops between two different sha256sums.

Here's an example of the diff. https://gist.github.com/jadunham1/5ca349895502aaf6be7eebf840b1bfc5
If I apply this it will just do the revert in an apply or two back to the old way.  It seems that the API does not preserve ordering of these yaml configs.

### Expected Behavior
No differences in plan between runs

### Actual Behavior
Differences in plan/apply ~50% of the time

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Create a workflow with multiple prometheus verification timeseries to watch and metric thresholds set
2. `terraform apply`

### Important Factoids
This only happens on workflows with verification providers and so far only prometheus verifications that I know of.  It only happens when there are multiple verifications in a single verification provider.
It is easy to reproduce by just curling the output of the yaml setup-as-code endpoint and looking at the diff, it changes it's ordering.

**Comment by raj-dhamsaniya** [comment]
we are having the same issue and this is reproducible.

**Comment by micahlmartin** [comment]
Thank you @jadunham1 and @raj-dhamsaniya. I've opened an internal ticket with the engineering team to fix this in the underlying API. https://harness.atlassian.net/browse/SWAT-7337.

**Comment by micahlmartin** [comment]
This is now fixed and in production.
