### ISSUE TITLE
Cannot Specify Delegate Selectors with Service Account in Harness NG Kubernetes Connector

### ISSUE THREAD

**Issue by jrmash** [harness/terraform-provider-harness#126]
Configuring a Kubernetes connector that uses a service account via Terraform does not offer any means of specifying delegate selectors. This is possible via the Harness NG web interface:

![image](https://user-images.githubusercontent.com/2574997/167687771-fba0d808-1d83-443a-9000-806d2e0b0c57.png)

### Terraform Version
```
Terraform v1.1.9 on darwin_amd64
+ provider registry.terraform.io/harness/harness v0.2.4
```

### Affected Resource(s)
```
harness_platform_connector_kubernetes
```

### Terraform Configuration Files
```hcl
resource "harness_platform_connector_kubernetes" "example" {
    identifier  = "example"
    name        = "example"
    org_id      = "example_org"
    tags        = []

    service_account {
        master_url                = "https://k8s.example.com"
        service_account_token_ref = "org.example_secret_ref"
    }
}
```

### Expected Behavior
It is possible to specify `delegate_selectors` when using a `service_account` in a manner consistent with the web interface.

### Actual Behavior
It is not possible to specify `delegate_selectors` when using a `service_account` in a manner consistent with the web interface.

### Important Factoids
Delegate selector settings are wiped when changes are applied to the Kubernetes connector's configuration.

**Comment by rijajoo** [comment]
Issue has been fixed in v0.2.13, https://github.com/harness/terraform-provider-harness/blob/main/CHANGELOG.md#0213.
