### ISSUE TITLE
Support for harness_platform_connector_vault

### ISSUE THREAD

**Issue by hwh57** [harness/terraform-provider-harness#146]
Enhancement request to support harness_platform_connector_vault to use Hashicorp Vault as a secret manager. This looks like it is supported by the API but is yet to make it into this provider.

**Comment by nialdaly** [comment]
I tried to have a look at this @hwh57 but it seems that Vault hasn't yet been included in the `ConnectorInfo` struct on the [harness-go-sdk](https://github.com/harness/harness-go-sdk/blob/main/harness/nextgen/model_connector_info.go). This may be a blocker for adding it to `terraform-provider-harness`?

**Comment by micahlmartin** [comment]
@rathodmeetsatish IS this something you can assist with in the SDK?

**Comment by rathodmeetsatish** [comment]
vault connector is available in latest version https://github.com/harness/terraform-provider-harness/pull/250
