### ISSUE TITLE
Provider Panic when creating k8s service

### ISSUE THREAD

**Issue by abstract-base-method** [harness/terraform-provider-harness#148]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.1.9
on darwin_arm64

### Affected Resource(s)
Please list the resources as a list, for example:
- harness_service_kubernetes

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "harness_service_kubernetes" "app" {
  app_id       = harness_application.app.id
  name         = "testapp"
  helm_version = "V3"
  description  = "a fresh service named \"${local.service_name}\" for a fresh idea"
}
```

### Panic Output
https://gist.github.com/abstract-base-method/63a5cd3a68560d3c23cbac53413b50fd

### Expected Behavior
Service should have been created.

### Actual Behavior
crash happened.

### Steps to Reproduce
1. create an application with a Kubernetes service within it using terraform2. 
1. terraform apply2.

**Comment by micahlmartin** [comment]
Hi James! Thanks for sending this over. Looking at the code it's possible that the application you're referencing couldn't be found. I'm adding extra error handling in that spot. Can you verify the application actually got created?

**Comment by abstract-base-method** [comment]
The application is created, but the service is not. I can see in the trace logs that the app create call is successful, and the `Get` call to the app it returns successfully as well.

**Comment by abstract-base-method** [comment]
This was due to a race condition in the `terraform apply`. By making the `depends_on` clause explicit the issue was resolved.
