### ISSUE TITLE
Harness Cannot Connect to Backend API After Many Retries

### ISSUE THREAD

**Issue by mphammer** [harness/terraform-provider-harness#152]
### Terraform Version
Version 0.14.8

### Affected Resource(s)
All harness terraform resources. 

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.14.8"
  required_providers {
    ...
    harness = {
      source  = "harness/harness"
      version = "0.0.17"
    }
  }
  }
}

provider "harness" {
  endpoint   = "https://app.harness.io/gateway"
  account_id = <account_id>
  api_key    = <api_key>
}
```

### Debug Output
https://gist.github.com/mphammer/1d858fe15f13c5552f9e7e80e81d4686

### Expected Behavior
The Terraform Plan completes. 

### Actual Behavior
The Terraform Plan has trouble connecting to the graphql API and errors after many attempts. 
This was not an issue all of last week but then it started occurring on Friday and it is still present today.

**Comment by micahlmartin** [comment]
@mphammer I think this issue is related to using a version that is very old. The latest is `0.2.11`.

**Comment by mphammer** [comment]
@micahlmartin I upgraded to 0.2.11 and the issue did not go away. 

Plan Output:  

```
Error: [POST https://app.harness.io/gateway/api/graphql?accountId=<account_id> giving up after 11 attempt(s)

Error: [POST https://app.harness.io/gateway/api/graphql?accountId=<account_id> giving up after 11 attempt(s)

  on .terraform/modules/<module>/modules/<sub_module>/file.tf line 2, in data "harness_application" "<app>":
   2: data "harness_application" "<app>"

Operation failed: failed running terraform plan (exit 1)
```

**Comment by micahlmartin** [comment]
@mphammer is the config you posted the entire module you're running?
