### ISSUE TITLE
Resource Group panic from Array out of bounds

### ISSUE THREAD

**Issue by itsdax** [harness/terraform-provider-harness#178]
There's a bug in [resource groups](https://github.com/harness/terraform-provider-harness/blob/ea83f9fb2fb770e3fb46d12dddb41f8201b54854/internal/service/platform/resource_group/resource_group.go#L325) that is causing an array out of bounds.

The [harness provider documentation](https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_resource_group#nested-schema-for-resource_filterresources) indicates that `attribute_filter` is optional under `resource_filter.resources`. However, if you don't specify a `attribute_filter`, `v["attribute_filter"]` still exists and is casted to an empty list and `attr.([]interface{})[0]` will cause an array out of bounds.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.14.11

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "harness_platform_resource_group" "test" {
  ...
  ...
  ...
  resource_filter {
    include_all_resources = false
    resources {
      resource_type = "CONNECTOR"
    }
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by rathodmeetsatish** [comment]
This issue is fixed in v0.3.3
