### ISSUE TITLE
GitOps Resources Don't Work.....

### ISSUE THREAD

**Issue by steve-gray** [harness/terraform-provider-harness#260]
I'm unable to get any of the `harness_gitops_` prefixed resources to work. It appears either the underlying Go SDK API's don't permit the use of PAT/SAT keys and require a bearer token, or that the keys aren't being passed around internally.

I've tried a few options here in different directions, but ultimately we just want to have a terraform script create some Harness resources and trigger them. It seems this is potentially a trick too much though for the current state of play?

**Comment by steve-gray** [comment]
Yeah, I've confirmed this with the Go SDK locally. The fix is in addition to *these* lines....

```
	ctx = context.WithValue(ctx, nextgen.ContextAccessToken, hh.EnvVars.BearerToken.Get())
```

You need to follow them with:
```
	ctx = context.WithValue(ctx, nextgen.ContextAPIKey, nextgen.APIKey{
		Key: apiKey,
	})
```

(Where apiKey is from the terraform provider properties). Ideally you should remove any access of environment variables from these resource definitions and do that kind of defaulting in the Terraform provider function itself, not inside the individual resource stoo.

**Comment by manavjot-harness** [comment]
Hi @steve-gray , this has been fixed. Now GitOps resources support the pat token.

**Comment by steve-gray** [comment]
I can confirm this is working, and was able to deploy a Gitops agent. 

@manavjot-harness  - is there a resource to configure the association between an agent and environment anywhere?

**Comment by manavjot-harness** [comment]
@steve-gray No we don't have a resource for the association for agent and environment. But you can configure environments to use certain clusters from an agent.

Can you please elaborate on the use case?
