### ISSUE TITLE
Resource Import Examples -  Incorrect

### ISSUE THREAD

**Issue by steve-gray** [harness/terraform-provider-harness#262]
The documentation for importing resources is incorrect, seemingly across the board:

## Example
https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_service

Example given is:
```
# Import using service id
terraform import harness_platform_service.example <service_id>
```

Should be

```
# Import using service id
terraform import harness_platform_service.example <org_id>/<project_id>/<service_id>
```

If you follow the listed version, you'll get panics due to trying to split the string (line 197 of helpers/schema.go). 

EDIT: The code for this function internally makes this more obvious - so it should make its way into the docs. 
![image](https://user-images.githubusercontent.com/14563775/197432064-b25d6926-09f6-4a99-896e-ef1f80fd5109.png)

**Comment by rathodmeetsatish** [comment]
import examples are fixed in latest version https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_service. Thanks for reporting
