### ISSUE TITLE
Error creating a user

### ISSUE THREAD

**Issue by mmorejon** [harness/terraform-provider-harness#311]
### Terraform Version

```
$ terraform -v
Terraform v1.3.2
on darwin_arm64
```
### Affected Resource(s)
- harness_user

### Terraform Configuration Files
Not needed

### Panic Output
[crash.log](https://gist.github.com/mmorejon/b0a65a19019e4f3b75e3306c85119ff3)

### Expected Behavior
A new user was created in the account.

### Actual Behavior
I got a memory error in the console.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
No

### References
No

**Comment by rathodmeetsatish** [comment]
Can you please share the configuration you applied?

**Comment by mmorejon** [comment]
This is the `main.tf` file.

```
terraform {
  required_version = ">= 0.14.9"

  required_providers {
    harness = {
      source  = "harness/harness"
      version = "~> 0.7"
    }
  }
}

provider "harness" {
  endpoint = "https://app.harness.io/gateway"
}

resource "harness_user" "manuel_morejon" {
  name  = "Manuel Morejon"
  email  = "manuel.morejon@......"
}
```

**Comment by mmorejon** [comment]
Any suggestion @rathodmeetsatish ?

**Comment by rathodmeetsatish** [comment]
@mmorejon you have not provided account_id and api_key in provider config. Also if you use the latest version you will get a proper error message. Please refer to example usage here https://registry.terraform.io/providers/harness/harness/latest/docs to see have to provide provider configs

**Comment by mmorejon** [comment]
Hi @rathodmeetsatish .
I'm using environment variables for the `account_id` and the `platform_api_key` to configure Harness provider Next Generation.
I updated Harnes provider from version `0.7.1` to `0.9.1`, and now I have a different error message:
```
harness_user.manuel_morejon: Creating...
╷
│ Error: unauthorized
```

I noted `harness_user` belongs to the First Generation group. Do I need a second provider for the First Generation too?
If this is the case, how can I configure both providers to use environment values?

**Comment by rathodmeetsatish** [comment]
to use both first gen and next gen resources add both platform_api_key and api_key
provider "harness" {
  endpoint         = "https://app.harness.io/gateway"
  account_id       = "...."
  platform_api_key = "......"
  api_key    = "......"
}
here for platform_api_key please add api key generated in next gen and for api_key please add api key generated in firstgen
to create api key in first gen follow this doc https://docs.harness.io/article/smloyragsm-api-keys#create_an_api_key
to create api key in next gen follow this doc https://docs.harness.io/article/tdoad7xrh9-add-and-manage-api-keys

**Comment by mmorejon** [comment]
Thanks a lot for the support. The user was created.
