### ISSUE TITLE
Fail to import state

### ISSUE THREAD

**Issue by antonio-chang** [harness/terraform-provider-harness#55]
Hi there,

The Terraform Provider for Harness appears to be broken. We attempted to import the github connector and it threw some go-lang error stacks when using an import command.
We used this command - "import module.control.harness_connector.github_marqeta marqetajposharnessnextgen"
Please see more detail about our tfplan and errors in the attached photos.

<img width="1119" alt="Screen Shot 2022-01-04 at 3 24 42 PM" src="https://user-images.githubusercontent.com/61202696/148814808-cbaee22d-dbe9-45ab-b84f-c26eebcbfdb8.png">
<img width="1372" alt="Screen Shot 2022-01-04 at 3 25 13 PM" src="https://user-images.githubusercontent.com/61202696/148814815-5bb9cf63-eb1a-45ee-a4eb-f31b89886f76.png">
<img width="1667" alt="Screen Shot 2022-01-04 at 3 25 25 PM" src="https://user-images.githubusercontent.com/61202696/148814820-65d55ec8-4b09-49d7-a2ed-779f6238d035.png">

Ticket ref - https://support.harness.io/hc/en-us/requests/21831

**Comment by micahlmartin** [comment]
@antonio-chang what version of the provider are you using? I think the latest version 0.1.8 may have some bugs in the nextgen code. If that's the case, can you try 0.1.7?

**Comment by antonio-chang** [comment]
@micahlmartin, I think I was using 0.1.7.  You can see the last few line in the last pic, it says v0.1.7 plugin crashed.

**Comment by micahlmartin** [comment]
@antonio-chang I'm currently getting the error also. I think there were some changes in the API. I'm working to get a fix out for you

**Comment by micahlmartin** [comment]
@antonio-chang can you try with version 0.1.9?

**Comment by micahlmartin** [comment]
Closing this since it is over 30 days.
