### ISSUE TITLE
Failures seen in v0.1.14

### ISSUE THREAD

**Issue by sumodb** [harness/terraform-provider-harness#84]
We have been facing multiple issues with the latest harness provider version 0.1.14 while trying to run our harness terraform modules. Everything works fine on the older version 0.1.9 and breaks on this newest version. We have tested the latest version across four of our modules and each one is failing within its PLAN/APPLY phase.
 
### Terraform Version
Terraform v1.0.0
 
### Affected Resource(s)
 
1. harness_delegate_approval
2. harness_yaml_config
3. harness_service_kubernetes
4. harness_application
 
 
### Debug Output
1. harness_delegate_approval - The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call.
2. harness_yaml_config -  Error: received http status code '404'
3. harness_service_kubernetes - The argument "app_id" is required, but no definition was found
4. harness_application - The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call
 
 
### Expected Behavior
_Based on affected resources number list_
1. The plan should have succeeded without the plugin crash error
2. Apply should be succeeded without the HTTP 404 error
3. The plan should have succeeded with the env_id field set to be computed during the apply run
4. The plan should have succeeded without the plugin crash error
 
### Actual Behavior
_Based on affected resources number list_
1. The plan failed because the plugin encountered an error, and failed to respond to the plugin
2. Apply failed throwing HTTP 404 error
3. The plan failed because no definition was found for the env_id field
4. Plan failed because the plugin encountered an error, and failed to respond to the plugin
 
### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

**Comment by kclarkey** [comment]
Version 0.1.10 had some underlying provider config changes, namely the required removal of the trailing `/api` on the harness `endpoint` parameter.  Your 404 errors and failed responses are similar to those we received before we updated our provider config to remove the trailing `/api` path.

[Changelog Notes](https://github.com/harness/terraform-provider-harness/blob/main/CHANGELOG.md#0110) for reference.

**Comment by micahlmartin** [comment]
Thanks @kclarkey for pointing this out. I believe @sumodb and team discovered that to be their issue as well. Closing this for now.
