### ISSUE TITLE
Harness Expression doesn't reflect in the terraform provider

### ISSUE THREAD

**Issue by shubhadabirajdar** [harness/terraform-provider-harness#85]
Hi there,

Terraform provider does not support Expressions whereas Expressions are currently reflected in the Harness SDK.  We are deploying harness resources Service, Infrastructure definition, Workflows, pipelines through terraform. We are facing issue to undefine Expressions in Infrastructure definition.  

You can refer the error herewith,

module.harness-deploy.harness_infrastructure_definition.test-Infradef: Creating...
╷
│ Error: FAILED**: Invalid request: Expressions can't be empty with provisioner
│ 
│   with module.harness-deploy.harness_infrastructure_definition.test-Infradef,
│   on ../services.tf line 15, in resource "harness_infrastructure_definition" "test-Infradef":
│   15: resource "harness_infrastructure_definition" "test-Infradef" {

![tempsnip](https://user-images.githubusercontent.com/68539856/156000589-a63278cf-03f2-48e9-b41c-1fbe3877d10b.png)

Here we are not sure, how to provide Expressions through terraform. Since Expressions are not reflected in provider.  We are trying to deploy Harness pipeline and workflow through terraform. We are stuck here with Infrastructure definition Expression. 

Please help us here to resolve this issue.

**Comment by micahlmartin** [comment]
@shubhadabirajdar What field are you trying to set as an expression? It's not clear to me in the example here exactly what is happening.

**Comment by shubhadabirajdar** [comment]
@micahlmartin We are trying to add Infrastructure definition, deployment type is Lambda. We are deploying this harness through Terraform. Please check the reference herewith;

resource "harness_infrastructure_definition" "test-Infradef" {
  name                = "test-InfraDemo"
  app_id              = data.harness_application.app.id
  env_id              = harness_environment.devtest.id
  cloud_provider_type = "AWS"
  deployment_type     = "AWS_LAMBDA"
  aws_lambda {
   
    cloud_provider_name = "xyz"
    region = var.app_region
    iam_role = var.role_arn 
  
  }
 
  provisioner_name = "Test-provisioner"
  scoped_services = ["test-service"]
}
 The below three fields should go in Expression as per the Harness YAML predefined files. Please check the image as well. 
<img width="258" alt="image" src="https://user-images.githubusercontent.com/68539856/157600608-181e3936-ec64-447b-85ce-d3583987c723.png">

cloud_provider_name = "xyz"
    region = var.app_region
    iam_role = var.role_arn

**Comment by micahlmartin** [comment]
In terraform `${...}` is the template syntax. You have to escape it with `$${...}

**Comment by shubhadabirajdar** [comment]
Hi @micahlmartin  

As per the harness yaml syntax, We are trying to pass **region = var.app_region    iam_role = var.role_arn** in expression block only.

expressions {
  region = var.app_region
  iam_role = var.role_arn
}
However this is failing. Since we are not sure how to pass region, iam_role in expression in terraform. We have check terraform . harness documentation even, there is no details defined in provider for expression. 

We need to know the schema for expression since even documentation doesnt have the word expression at all. Please check the registry link herewith.

https://registry.terraform.io/providers/harness-io/harness/latest/docs/resources/infrastructure_definition#nestedblock--aws_lambda


Please let us know the solution here.

Thanks
