### ISSUE TITLE
Usage Link is Broken

### ISSUE THREAD

**Issue by suranc** [harness/terraform-provider-harness#91]
In the README, the link for "Provider usage" is broken.  Currently it points to https://registry.terraform.io/providers/harness/harness/latest/docs which gives 404.  It looks like it is a relic of the move from the harness-io org, since this link seems to work: https://registry.terraform.io/providers/harness-io/harness/latest/docs

**Comment by micahlmartin** [comment]
Yeah this has been a nightmare trying to move the repo. We have a ticket open with Hashicorp we're trying to get addressed. I may just need to move them back to harness-io unfortunately.

**Comment by micahlmartin** [comment]
This is now fixed!!
