### ISSUE TITLE
Issue utilizing v.0.1.15 provider

### ISSUE THREAD

**Issue by asheynkmantyler** [harness/terraform-provider-harness#92]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v1.0.9
on darwin_amd64
```

### Affected Resource(s)
Please list the resources as a list, for example:
terraform provider v0.1.15 for MAC and Linux

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    harness = {
      source  = "harness-io/harness"
      version = "0.1.15"
    }
  }
  required_version = ">=1.0.0"
}

```

When running terraform init, the following error appears:

```
Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/harness-io/harness v0.1.15 does not have a package available for your current platform, darwin_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different
│ platforms supported.
```

### Expected Behavior
Terraform should initialize properly

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

### Important Factoids
Same error appears when running on Linux, in Terraform Cloud

**Comment by micahlmartin** [comment]
There's currently an issue with the Terraform Registry we're working with Hashicorp to get fixed. For now you'll need to download the package directly from the github release

**Comment by sumodb** [comment]
@micahlmartin We do face similar issue when Jenkins calls the registry API to get provider metadata which ends up with HTTP 404 error. The endpoint [https://registry.terraform.io/v1/providers/harness-io/harness/0.1.15/download/linux/amd64] is throwing "{"errors":["signing key A1A83E0CC7A69F1D not found for harness-io"]}" error. Works fine for all rest of the versions expect 0.1.15.
 
Believe this is also caused due to the same Terraform registry issue which we are talking about.

**Comment by micahlmartin** [comment]
This has now been fixed. You should be able to use the provider with `harness/harness` instead of `harness-io/harness`
