### ISSUE TITLE
"Infrastructure Provisioners" Resource?

### ISSUE THREAD

**Issue by MrFishFinger** [harness/terraform-provider-harness#93]
Maybe I am missing something obvious, but is there a way to create a "Infrastructure Provisioners" for a given Application?

https://docs.harness.io/article/o22jx8amxb-add-an-infra-provisioner

![image](https://user-images.githubusercontent.com/4768596/157300776-3f558c47-e420-4215-a15f-05aeeaa272ef.png)

**Comment by micahlmartin** [comment]
@MrFishFinger you can achieve this today using the `harness_yaml_config` resource. Let me know if that makes sense.
